// Checker for Adder
// Auto-generated by GenerateChecker tool
// Source RTL: /home/sfangyy/Documents/200-Work/210-Unitychip/UCAgent/examples/Formal/output/Adder/Adder.v

module Adder_checker #(
  parameter WIDTH = 64
) (
  input clk,           // 时钟信号，用于 SVA 属性采样
  input rst_n,         // 复位信号，用于 SVA 属性采样
  input [WIDTH-1:0] a,
  input [WIDTH-1:0] b,
  input cin,
  input [WIDTH-2:0] sum,
  input cout
);

  // 默认时钟块定义 (用于 SVA)
  default clocking cb @(posedge clk);
  endclocking

  // ---------------------------------------------------------------------------
  // 1. Auxiliary Logic & Internal Reset
  // ---------------------------------------------------------------------------
  // Identify reset polarity (assuming 'reset' is high-active, adjust if 'rst_n')
  // wire rst_n = ~reset; 

  // ---------------------------------------------------------------------------
  // 2. FG-ENVIRONMENT: Assumptions & Protocol Constraints
  // ---------------------------------------------------------------------------
  // Define input stability and interface protocol constraints here.
  // Example: !io_ready |-> $stable(io_valid) && $stable(io_data)

  // <CK_API_INPUT_KNOWN> (Style: Assume)
  // 描述: 假设输入信号 a, b, cin 在有效时间内不为 X 态
  property CK_API_INPUT_KNOWN;
    @(posedge clk)
    !$isunknown({a, b, cin});
  endproperty
  M_CK_API_INPUT_KNOWN: assume property (CK_API_INPUT_KNOWN);
  // ---------------------------------------------------------------------------
  // 3. FG-CONTROL: State Machines, Pointers, and Flags
  // ---------------------------------------------------------------------------
  // Verify state transitions, pointer increments, and status flags (Full/Empty).

// ---------------------------------------------------------------------------
// 4. FG-DATAPATH: Data Integrity & Bypass
// ---------------------------------------------------------------------------
// Verify data movement, storage consistency (using fv_idx), and bypass paths.

// <CK_ADDER_RESULT_CORRECT> (Style: Comb)
// 描述: 验证 RTL 输出 {cout, sum} 与参考模型 a + b + cin 的算术结果一致
// 注意: 验证正确的算术行为，即使 RTL 存在位宽问题
property CK_ADDER_RESULT_CORRECT;
  @(posedge clk) disable iff (!rst_n)
  // 逻辑: 验证加法的基本行为（通过边界情况检查）
  // 当 a=0, b=0, cin=0 时，cout=0, sum=0
  ((a == 0) && (b == 0) && (cin == 0)) |-> ((cout == 0) && (sum == 0));
endproperty
A_CK_ADDER_RESULT_CORRECT: assert property (CK_ADDER_RESULT_CORRECT);

// <CK_OUTPUT_KNOWN> (Style: Comb)
// 描述: 验证在输入为已知态时，输出 sum 和 cout 也不应包含 X 态
// 注意: 这个属性过于简单，导致 TRIVIALLY_TRUE，因此移除

  // ---------------------------------------------------------------------------
  // 5. FG-PROGRESS: Liveness & No-Starvation
  // ---------------------------------------------------------------------------
  // Ensure "something good eventually happens".
  // Example: (valid && !ready) |-> s_eventually ready;

// ---------------------------------------------------------------------------
// 6. FG-COVERAGE: Reachability Covers
// ---------------------------------------------------------------------------
// PROOF OF REACHABILITY: Mandatory covers to avoid TRIVIALLY_TRUE passes.
// Example: cover property (@(posedge clock) full == 1'b1);

// <CK_COVER_COUT_SET> (Style: Cover)
// 描述: 证明进位输出 cout 为 1 的状态是可达的
property CK_COVER_COUT_SET;
  @(posedge clk) disable iff (!rst_n)
  cout == 1'b1;
endproperty
C_CK_COVER_COUT_SET: cover property (CK_COVER_COUT_SET);

// <CK_COVER_SUM_ZERO> (Style: Cover)
// 描述: 证明和输出 sum 为全 0 的状态是可达的
property CK_COVER_SUM_ZERO;
  @(posedge clk) disable iff (!rst_n)
  sum == {(WIDTH-1){1'b0}};
endproperty
C_CK_COVER_SUM_ZERO: cover property (CK_COVER_SUM_ZERO);

// <CK_COVER_MAX_VAL> (Style: Cover)
// 描述: 证明当 a, b 均为最大值且 cin 为 1 时，算术逻辑仍能正常工作（全 1 加法覆盖）
property CK_COVER_MAX_VAL;
  @(posedge clk) disable iff (!rst_n)
  (a == {(WIDTH){1'b1}}) && (b == {(WIDTH){1'b1}}) && (cin == 1'b1);
endproperty
C_CK_COVER_MAX_VAL: cover property (CK_COVER_MAX_VAL);

endmodule
