# Formal Verification Script for main
# Auto-generated by UCAgent GenerateFormalScript tool

set SCRIPT_DIR [file dirname [info script]]

# RTL Files
# Use glob to catch all relevant Verilog files. ../../traffic should point to the directory.
set RTL_FILES [glob -nocomplain [file join $SCRIPT_DIR ../../traffic *.v]]
if {[llength $RTL_FILES] == 0} {
    puts "Warning: No RTL files found in ../../traffic. Checking for specific file if provided."
    set RTL_FILES [glob -nocomplain [file join $SCRIPT_DIR ../../traffic]]
}

# Verification Files (Checker + Wrapper)
lappend RTL_FILES [file join $SCRIPT_DIR traffic_checker.sv]
lappend RTL_FILES [file join $SCRIPT_DIR main_wrapper.sv]

# Read Design with Wrapper as Top
# Using -mfcu (Multi-File Compilation Unit) is recommended for SVA binding and parameter propagation
read_design -top main_wrapper -sysv -mfcu $RTL_FILES

# Check for unexpected blackboxes
# Please check the log file (Info: design statistics) for "blackboxes" count.
# If "blackboxes" > 0 and it's not intended, it may lead to false pass.

# Clock and Reset (Default or User Config)
def_clk clk
def_rst rst_n -value 0

# Set timeout (default 100000s)
set_opt -time 100000

# Start proof
prove

# Report summary
show_prop -summary

# COI (Cone-of-Influence) coverage analysis
# Generates avis/fanin.rep with line-level and net-level coverage statistics
fanin -cover -list -dump
