# Formal Verification Script for {dut_name}
# Auto-generated by UCAgent GenerateFormalScript tool

set SCRIPT_DIR [file dirname [info script]]

# RTL Files
# Use glob to catch all relevant Verilog files. {rel_rtl_dir} should point to the directory.
set RTL_FILES [glob -nocomplain [file join $SCRIPT_DIR {rel_rtl_dir} *.v]]
if {{[llength $RTL_FILES] == 0}} {{
    puts "Warning: No RTL files found in {rel_rtl_dir}. Checking for specific file if provided."
    set RTL_FILES [glob -nocomplain [file join $SCRIPT_DIR {rel_rtl_dir}]]
}}

# Verification Files (Checker + Wrapper)
lappend RTL_FILES [file join $SCRIPT_DIR {checker_basename}]
lappend RTL_FILES [file join $SCRIPT_DIR {wrapper_basename}]

# Read Design with Wrapper as Top
# Using -mfcu (Multi-File Compilation Unit) is recommended for SVA binding and parameter propagation
read_design -top {top_module} -sysv -mfcu $RTL_FILES

# Check for unexpected blackboxes
# Please check the log file (Info: design statistics) for "blackboxes" count.
# If "blackboxes" > 0 and it's not intended, it may lead to false pass.

# Clock and Reset (Default or User Config)
{clock_config}
{reset_config}

# Set timeout (default 100000s)
set_opt -time 100000

# Start proof
prove

# Report summary
show_prop -summary

# COI (Cone-of-Influence) coverage analysis
# Generates avis/fanin.rep with line-level and net-level coverage statistics
fanin -cover -list -dump
