// Wrapper for Adder
// Auto-generated by GenerateChecker tool
// Instances DUT and checker

module Adder_wrapper #(
  parameter WIDTH = 64
) (
  input clk,           // 时钟信号，用于 SVA 属性采样
  input rst_n,         // 复位信号，用于 SVA 属性采样
  input [WIDTH-1:0] a,
  input [WIDTH-1:0] b,
  input cin,
  output [WIDTH-2:0] sum,
  output cout
);

  // ---------------------------------------------------------------------------
  // DUT Instantiation
  // ---------------------------------------------------------------------------
  Adder #(
    .WIDTH(WIDTH)
  ) dut (
    .a(a),
    .b(b),
    .cin(cin),
    .sum(sum),
    .cout(cout)
  );

  // ---------------------------------------------------------------------------
  // White-box Verification: Internal Signals Extraction
  // ---------------------------------------------------------------------------
  // [LLM-TODO]: Extract critical internal signals using 'dut.signal' paths.
  // Example: wire [4:0] dut_ptr = dut.ptr_reg;
  //          wire [3:0] dut_state = dut.fsm_state;

  // ---------------------------------------------------------------------------
  // Symbolic Indexing Logic (for Arrays/FIFOs/RegFiles)
  // ---------------------------------------------------------------------------
  
  // input [INDEX_WIDTH-1:0] fv_idx; // Controlled by Formal Tool
  // wire [DATA_WIDTH-1:0] fv_mon_data = entries[fv_idx];

  // ---------------------------------------------------------------------------
  // Checker Instantiation
  // ---------------------------------------------------------------------------
  Adder_checker #(
    .WIDTH(WIDTH)
  ) checker_inst (
    .clk(clk),
    .rst_n(rst_n),
    .a(a),
    .b(b),
    .cin(cin),
    .sum(sum),
    .cout(cout)
    // [LLM-TODO]: Connect white-box and symbolic signals here
  );

endmodule
