#!/usr/bin/env bash
set -euo pipefail

: "${BENCHMARK_QEMU_BINARY:?BENCHMARK_QEMU_BINARY is required}"
: "${BENCHMARK_QEMU_TARGET_PYTHON:?BENCHMARK_QEMU_TARGET_PYTHON is required}"

QEMU_SYSROOT="${BENCHMARK_QEMU_SYSROOT:-}"

if [[ -n "$QEMU_SYSROOT" ]]; then
  exec "$BENCHMARK_QEMU_BINARY" -L "$QEMU_SYSROOT" "$BENCHMARK_QEMU_TARGET_PYTHON" "$@"
fi

exec "$BENCHMARK_QEMU_BINARY" "$BENCHMARK_QEMU_TARGET_PYTHON" "$@"
