
model_type: openai
openai:
  model_name: Qwen/Qwen3-32B
  openai_api_key: "EMPTY_API_KEY"
  openai_api_base: "http://127.0.0.1:8000/v1"
  model_kwargs:
    stop: ["."]

mission:
  name: "{DUT}芯片验证任务"
  prompt:
    system: >
      你是一位资深的芯片验证工程师和AI测试专家，专门从事数字电路的功能验证工作。
      你具备深厚的硬件设计理解能力，还具有软件测试方法论知识，以及基于现代验证框架的实践经验。
      
      **核心任务目标：**
      完成`{DUT}`数字电路的全面功能验证，确保设计的正确性、鲁棒性和可靠性。
      
      **工作框架：**
      验证任务采用分阶段渐进式方法，每个阶段都有明确的交付物和质量标准。
      使用工具`CurrentTips`获取当前阶段的详细任务指导，严格按照验证流程执行。
      
      **标准流程：**
      验证分为7个阶段，每个阶段都有具体任务：
      1. **需求分析** - 理解验证要求，制定验证计划
      2. **功能理解** - 深入了解芯片功能和接口定义
      3. **功能分析** - 把复杂功能拆成可测试的小块
      4. **设计接口** - 创建测试API，让测试更简单
      5. **建立覆盖率** - 跟踪哪些功能已经测试了
      6. **创建模板** - 准备测试框架
      7. **执行测试** - 写真实测试，找出bug并分析
      
      **工作原则：**
      - 按步骤有序进行，每步完成后用`Check`工具验证
      - 测试失败时，优先怀疑是芯片设计问题，不是测试问题
      - 发现bug要详细分析：什么问题、为什么出现、如何修复
      - 写清楚、简单易懂的代码和文档
      
      **必须使用的工具：**
      - `CurrentTips`: 获取当前步骤的具体指导
      - `Check`: 检查当前步骤是否完成
      - `Complete`: 完成当前步骤，进入下一步
      - `ReadTextFile`: 读取文件内容
      - 其他文件操作和搜索工具按需使用
      
      现在开始你的验证工作！

template: unity_test
un_write_dirs:
  - "{DUT}"
  - "Guide_Doc"
write_dirs:
  - "{OUT}"

embed:
  model: "Qwen/Qwen3-Embedding-8B"
  openai_base_url: http://10.156.154.242:8001/v1
  api_key: "EMPTY_API_KEY"
  dims: 4096

mcp_server:
  init_prompt: >
    欢迎使用UCAgent芯片验证平台！

    **你的角色：**
    你是专业的芯片验证AI助手，负责测试数字电路功能。

    **开始工作：**
    1. 先调用`RoleInfo`工具了解你的角色和当前任务
    2. 使用`CurrentTips`工具获取当前阶段的具体任务
    3. 用其他工具完成文件读写、搜索等操作

    **工作流程：**
    验证分7个阶段：需求分析 → 功能理解 → 功能分析 → API设计 → 覆盖率模型 → 测试模板 → 执行测试

    **重要工具：**
    - `CurrentTips`: 获取当前阶段任务指导
    - `Check`: 检查阶段是否完成(会自动运行pytest等)
    - `Complete`: 完成当前阶段进入下一阶段
    - `ReadTextFile`: 读取文件(必须用这个，否则我不知道你读了什么)
    - 文件写入：你可以选择合适的工具

    **质量保证：**
    - 每个阶段完成后必须用`Check`工具验证
    - 如果测试发现bug，要详细分析原因和修复方案
    - 包括：问题描述、根本原因、影响范围、修复建议

    **核心原则：**
    - 按阶段有序推进
    - 注重代码和文档质量
    - 深入分析发现的问题
    - 生成实用、可维护的验证代码

    现在开始你的芯片验证工作！

stage:
  - name: requirement_analysis_and_planning
    desc: "需求分析与验证规划"
    task:
      - "第1步：读取{DUT}/README.md，理解用户的验证要求"
      - "第2步：确定验证目标 - 需要测试哪些功能？输入输出是什么？"
      - "第3步：识别风险点 - 哪些地方容易出错？边界条件有哪些？"
      - "第4步：制定验证计划 - 如何系统地测试所有功能？"
      - "第5步：写入验证规划文档到{OUT}/{DUT}_verification_needs_and_plan.md"
      - "注意：{DUT}中可能有隐藏bug，测试失败时请分析是否为设计缺陷"
      - "完成后使用Check工具检测，通过后用Complete进入下一阶段"
    reference_files:
      - "{DUT}/README.md"
    output_files:
      - "{OUT}/{DUT}_verification_needs_and_plan.md"

  - name: dut_function_understanding
    desc: "{DUT}功能理解"
    task:
      - "第1步：读取{DUT}/README.md，了解芯片基本信息"
      - "第2步：读取{DUT}/__init__.py，理解代码接口定义"
      - "第3步：分析输入输出端口 - 每个端口的作用是什么？"
      - "第4步：确定芯片类型 - 是时序电路(需要时钟)还是组合电路？"
      - "第5步：整理基本信息，写入{OUT}/{DUT}_basic_info.md"
      - "目标：为后续阶段提供清晰的芯片基础信息"
    reference_files:
      - "{DUT}/README.md"
      - "{DUT}/__init__.py"
    output_files:
      - "{OUT}/{DUT}_basic_info.md"

  - name: functional_specification_analysis
    desc: "功能规格分析与测试点定义"
    task:
      - "目标：将芯片功能拆解成可测试的小块，为后续测试做准备"
      - "第1步：阅读所有相关文档，理解芯片完整功能"
      - "第2步：按功能模块分组，每组用<FG-名称>标记"
      - "第3步：每组内定义具体功能点，用<FC-名称>标记"
      - "第4步：每个功能点设计检测点，用<CK-名称>标记"
      - "第5步：写入{OUT}/{DUT}_functions_and_checks.md"
      - "重要：标签格式必须正确，这是后续自动化测试的基础"
      - "参考Guide_Doc/dut_functions_and_checks.md了解标准格式"
    reference_files:
      - "Guide_Doc/dut_functions_and_checks.md"
      - "{DUT}/*.md"
      - "{DUT}/__init__.py"
      - "{OUT}/{DUT}_basic_info.md"
      - "{OUT}/{DUT}_verification_needs_and_plan.md"
    output_files:
      - "{OUT}/{DUT}_functions_and_checks.md"
    stage:
      - name: functional_grouping
        desc: "功能分组与层次划分"
        task:
          - "基于{DUT}功能，将相关功能归类成组"
          - "为每组定义<FG-组名>标签，组名要有意义"
          - "创建文档框架，先完成分组部分"
          - "例如：加法器可分为<FG-BASIC>基础运算，<FG-OVERFLOW>溢出处理等"
        checker:
          - name: group_structure_check
            clss: "UnityChipCheckerLabelStructure"
            args:
              doc_file: "{OUT}/{DUT}_functions_and_checks.md"
              leaf_node: "FG"
              min_groups: 1
      - name: function_point_definition
        desc: "具体功能点识别与定义"
        task:
          - "在每个功能分组内，定义具体的功能点"
          - "用<FC-功能名>标签标记每个功能"
          - "确保覆盖该组的所有重要功能"
          - "例如：基础运算组可包含<FC-ADD>加法，<FC-ZERO>零值处理等"
        checker:
          - name: function_point_check
            clss: "UnityChipCheckerLabelStructure"
            args:
              doc_file: "{OUT}/{DUT}_functions_and_checks.md"
              leaf_node: "FC"
              min_groups: 1
      - name: check_point_design
        desc: "检测点设计与定义"
        task:
          - "为每个功能点设计具体的检测点"
          - "用<CK-检测名>标签标记，如<CK-BASIC>基本功能，<CK-BOUNDARY>边界条件"
          - "检测点要包含：正常情况、边界条件、异常情况"
          - "标签独立成行，与标题用空行分隔"
          - "完成完整的功能分析文档"
        checker:
          - name: check_point_check
            clss: "UnityChipCheckerLabelStructure"
            args:
              doc_file: "{OUT}/{DUT}_functions_and_checks.md"
              leaf_node: "CK"
              min_groups: 1

  - name: testbench_infrastructure_design
    desc: "测试平台基础架构设计"
    task:
      - "目标：创建测试API接口，让后续测试更简单"
      - "第1步：分析{DUT}的底层接口和工作方式"
      - "第2步：设计create_dut()函数 - 负责创建和初始化芯片实例"
      - "第3步：配置时钟(时序电路需要，组合电路不需要)"
      - "第4步：实现dut fixture - 管理测试的完整生命周期"
      - "第5步：创建API函数 - 以'api_'开头，封装常用操作"
      - "第6步：写入{OUT}/tests/{DUT}_api.py"
      - "原则：让测试人员使用简单的API，而不是复杂的底层信号"
      - "参考Guide_Doc/dut_fixture_and_api.md了解标准写法"
    stage:
     - name: dut_creation_implementation
       desc: "DUT创建函数实现"
       task:
         - "实现create_dut()函数，完成芯片的基础创建"
         - "根据芯片类型配置时钟：时序电路用InitClock，组合电路不用"
         - "确保创建函数能正常工作"
       checker:
         - name: dut_creation_check
           clss: "UnityChipCheckerDutCreation"
           args:
             api_file: "{OUT}/tests/{DUT}_api.py"
       reference_files:
         - "Guide_Doc/dut_fixture_and_api.md"
     - name: pytest_fixture_implementation
       desc: "pytest fixture和基础API实现"
       task:
         - "实现dut fixture，包含完整的生命周期管理"
         - "至少实现1个基础API函数(以api_开头)"
         - "确保fixture能正确初始化和清理芯片"
       checker:
         - name: fixture_check
           clss: "UnityChipCheckerDutApi"
           args:
             api_file: "{OUT}/tests/{DUT}_api.py"
             min_apis: 1
       reference_files:
         - "Guide_Doc/dut_fixture_and_api.md"

  - name: coverage_model_implementation
    desc: "功能覆盖率模型实现"
    task:
      - "目标：创建覆盖率统计系统，跟踪哪些功能已测试"
      - "第1步：读取功能分析文档{OUT}/{DUT}_functions_and_checks.md"
      - "第2步：为每个功能分组<FG-*>创建CovGroup覆盖组"
      - "第3步：为每个功能点<FC-*>添加watch_point监测点"
      - "第4步：为每个检测点<CK-*>实现检查函数(用lambda)"
      - "第5步：实现get_coverage_groups(dut=None)主函数"
      - "第6步：写入{OUT}/tests/{DUT}_function_coverage_def.py"
      - "关键：检查函数要使用dut对象引用，不要用值(如dut而不是dut.a.value)"
      - "参考Guide_Doc/dut_function_coverage_def.md了解实现方法"
    stage:
      - name: coverage_group_creation
        desc: "功能覆盖组创建"
        task:
          - "为每个功能分组<FG-*>创建对应的CovGroup对象"
          - "实现get_coverage_groups(dut=None)基础框架"
          - "确保覆盖组可以正常创建和访问"
        checker:
          - name: coverage_group_check
            clss: "UnityChipCheckerCoverageGroups"
            args:
              group_file: "{OUT}/tests/{DUT}_function_coverage_def.py"
              min_groups: 1
        reference_files:
          - "Guide_Doc/dut_function_coverage_def.md"

      - name: coverage_check_implementation
        desc: "覆盖率检查点实现"
        task:
          - "为每个功能点添加watch_point和检查函数"
          - "用lambda函数实现检查逻辑，传递引用参数(dut对象)"
          - "完成完整的覆盖率定义"
        checker:
          - name: coverage_implementation_check
            clss: "UnityChipCheckerCoverGroup"
            args:
              test_path: "{OUT}/tests"
              group_file: "{OUT}/tests/{DUT}_function_coverage_def.py"
              min_groups: 1
        reference_files:
          - "Guide_Doc/dut_function_coverage_def.md"

  - name: test_framework_scaffolding
    desc: "测试框架脚手架构建"
    task:
      - "目标：创建测试用例模板，为实际测试做准备"
      - "第1步：分析功能文档{OUT}/{DUT}_functions_and_checks.md的所有测试点"
      - "第2步：创建测试文件test_<名称>.py，文件名要有意义"
      - "第3步：每个测试函数以test_开头，参数为dut(pytest fixture)"
      - "第4步：添加覆盖率标记：dut.fc_cover['FG-XXX'].mark_function('FC-YYY', test_func, ['CK-ZZZ'])"
      - "第5步：加入详细的TODO注释说明要测什么"
      - "第6步：添加assert False, 'Not implemented'防止意外通过"
      - "确保：每个功能点<FC-*>至少有一个测试用例"
      - "参考Guide_Doc/dut_test_template.md了解模板格式"
    checker:
      - name: template_check
        clss: "UnityChipCheckerTestTemplate"
        args:
          doc_func_check: "{OUT}/{DUT}_functions_and_checks.md"
          doc_bug_analysis: "{OUT}/{DUT}_bug_analysis.md"
          test_dir: "{OUT}/tests"
          min_tests: 1
        extra_args:
          fail_msg: "测试模板创建不符合规范。检查：1)测试文件名以'test_'开头 2)正确导入API模块 3)包含覆盖率标记 4)有详细TODO注释 5)有防意外通过的断言。参考Guide_Doc/dut_test_template.md和examples了解正确格式。"
          pass_msg: "测试模板创建成功！测试结构规范，覆盖率标记完整。"
          max_try: 10
    reference_files:
      - "Guide_Doc/dut_test_template.md"

  - name: comprehensive_verification_execution
    desc: "全面验证执行与缺陷分析"
    task:
      - "目标：将测试模板填充为真实测试，发现并分析芯片bug"
      - "第1步：理解芯片完整功能和预期行为"
      - "第2步：将空的测试模板填充为可执行代码"
      - "第3步：使用API接口调用芯片功能，避免直接操作底层信号"
      - "第4步：设计充分的测试数据：典型值、边界值、特殊值"
      - "第5步：添加断言检查输出是否正确"
      - "第6步：每完成一个测试立即用Check验证"
      - "第7步：分析测试结果："
      - "  - 如果Pass：测试正确，继续下一个"
      - "  - 如果Fail但合理：可能发现了芯片bug，分析并记录到{OUT}/{DUT}_bug_analysis.md"
      - "  - 如果Fail不合理：修正测试逻辑"
      - "重要：测试失败时，优先怀疑是芯片设计问题，不要急于修改测试"
      - "参考Guide_Doc/dut_test_case.md和dut_bug_analysis.md了解实现方法"
    checker:
      - name: test_check
        clss: "UnityChipCheckerTestCase"
        args:
          doc_func_check: "{OUT}/{DUT}_functions_and_checks.md"
          doc_bug_analysis: "{OUT}/{DUT}_bug_analysis.md"
          test_dir: "{OUT}/tests"
          min_tests: 1
        extra_args:
          fail_msg: "测试实现不符合要求。检查：1)测试逻辑是否正确 2)是否使用API而非直接信号操作 3)测试数据是否充分 4)断言是否有效 5)覆盖率标记是否正确 6)发现的bug是否详细分析。参考Guide_Doc/dut_test_case.md和examples了解正确方法。"
          pass_msg: "测试实现成功！测试逻辑正确，验证全面，bug分析详尽。"
          max_try: -1
    reference_files:
      - "Guide_Doc/dut_test_case.md"
      - "Guide_Doc/dut_bug_analysis.md"
